/**
 * Fake Claude Code subprocess for testing.
 * Mimics `claude -p --output-format stream-json` behavior.
 *
 * Set FAKE_CLAUDE_SCENARIO env var to control behavior:
 *   - "success" (default): emits events, creates a file, exits 0
 *   - "failure": emits events, exits 1
 *   - "timeout": hangs forever (for testing timeout handling)
 *   - "partial": emits partial output then crashes
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const scenario = process.env.FAKE_CLAUDE_SCENARIO || 'success';

function emit(obj: Record<string, unknown>) {
  process.stdout.write(JSON.stringify(obj) + '\n');
}

async function run() {
  // Init event
  emit({ type: 'system', subtype: 'init', session_id: 'fake-session-123' });

  switch (scenario) {
    case 'success': {
      emit({
        type: 'assistant',
        message: { content: [{ type: 'text', text: 'I will implement this task.' }] },
      });

      // Simulate creating a file
      const filePath = join(process.cwd(), 'jiranimo-test-output.txt');
      writeFileSync(filePath, 'Generated by fake Claude\n');

      emit({
        type: 'assistant',
        message: { content: [{ type: 'text', text: 'Task implemented successfully.' }] },
      });

      emit({
        type: 'result',
        subtype: 'success',
        result: 'Task completed. Created jiranimo-test-output.txt',
        total_cost_usd: 0.42,
        session_id: 'fake-session-123',
        duration_ms: 1500,
      });

      process.exit(0);
      break;
    }

    case 'failure': {
      emit({
        type: 'assistant',
        message: { content: [{ type: 'text', text: 'Attempting to implement...' }] },
      });

      emit({
        type: 'result',
        subtype: 'error',
        result: 'Failed to implement: could not understand the requirements',
        total_cost_usd: 0.15,
        session_id: 'fake-session-123',
      });

      process.exit(1);
      break;
    }

    case 'timeout': {
      emit({
        type: 'assistant',
        message: { content: [{ type: 'text', text: 'Working on it...' }] },
      });
      // Hang forever
      await new Promise(() => {});
      break;
    }

    case 'partial': {
      emit({
        type: 'assistant',
        message: { content: [{ type: 'text', text: 'Starting work...' }] },
      });
      // Crash mid-stream
      process.exit(2);
      break;
    }

    default:
      process.stderr.write(`Unknown scenario: ${scenario}\n`);
      process.exit(99);
  }
}

run();
