#!/usr/bin/env node
/**
 * Fake Claude Code subprocess (ESM, no tsx needed).
 * Mimics `claude -p --output-format stream-json`.
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const scenario = process.env.FAKE_CLAUDE_SCENARIO || 'success';

function emit(obj) {
  process.stdout.write(JSON.stringify(obj) + '\n');
}

if (scenario === 'success') {
  emit({ type: 'system', subtype: 'init', session_id: 'fake-session-123' });
  emit({ type: 'assistant', message: { content: [{ type: 'text', text: 'I will implement this task.' }] } });
  writeFileSync(join(process.cwd(), 'jiranimo-test-output.txt'), 'Generated by fake Claude\n');
  emit({ type: 'assistant', message: { content: [{ type: 'text', text: 'Task implemented successfully.' }] } });
  emit({ type: 'result', subtype: 'success', result: 'Task completed. Created jiranimo-test-output.txt', total_cost_usd: 0.42, session_id: 'fake-session-123', duration_ms: 1500 });
  process.exit(0);
} else if (scenario === 'failure') {
  emit({ type: 'system', subtype: 'init', session_id: 'fake-session-123' });
  emit({ type: 'result', subtype: 'error', result: 'Failed to implement', total_cost_usd: 0.15, session_id: 'fake-session-123' });
  process.exit(1);
} else if (scenario === 'timeout') {
  emit({ type: 'system', subtype: 'init', session_id: 'fake-session-123' });
  setTimeout(() => {}, 999999);
} else {
  process.exit(99);
}
