import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import type { PrResult } from './types.js';

const exec = promisify(execFile);

export interface CreatePrOptions {
  cwd: string;
  baseBranch: string;
  headBranch: string;
  title: string;
  body: string;
  githubRepo?: string;
  draft?: boolean;
}

export async function createDraftPr(options: CreatePrOptions): Promise<PrResult> {
  const args = [
    'pr', 'create',
    '--title', options.title,
    '--body', options.body,
    '--base', options.baseBranch,
    '--head', options.headBranch,
  ];

  if (options.draft !== false) {
    args.push('--draft');
  }

  if (options.githubRepo) {
    args.push('--repo', options.githubRepo);
  }

  const { stdout } = await exec('gh', args, { cwd: options.cwd });
  const url = stdout.trim();

  // Extract PR number from URL (e.g., https://github.com/owner/repo/pull/42)
  const match = url.match(/\/pull\/(\d+)/);
  const number = match ? parseInt(match[1], 10) : 0;

  return { url, number };
}

export function buildPrTitle(issueKey: string, summary: string): string {
  return `[${issueKey}] ${summary}`;
}

export function buildPrBody(options: {
  issueKey: string;
  summary: string;
  description: string;
  jiraUrl: string;
  resultText: string;
  costUsd?: number;
  durationMs?: number;
}): string {
  const lines: string[] = [
    `## Summary`,
    `Automated implementation of [${options.issueKey}](${options.jiraUrl}): ${options.summary}`,
    '',
    `## Description`,
    options.description.slice(0, 500),
    '',
    `## Implementation Notes`,
    options.resultText.slice(0, 1000),
    '',
    `## Metadata`,
    `- Jira Task: [${options.issueKey}](${options.jiraUrl})`,
    `- Generated by: Jiranimo + Claude Code`,
  ];

  if (options.costUsd !== undefined) {
    lines.push(`- Cost: $${options.costUsd.toFixed(2)}`);
  }
  if (options.durationMs !== undefined) {
    const secs = Math.round(options.durationMs / 1000);
    const mins = Math.floor(secs / 60);
    const remainSecs = secs % 60;
    lines.push(`- Duration: ${mins}m ${remainSecs}s`);
  }

  lines.push('', '---', '> This PR was automatically generated by Jiranimo. Please review carefully before merging.');

  return lines.join('\n');
}
